### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by signed-log**
Untested attempt to do something for #5 

Can't test it, and it requires rebuild for every `appsettings.json` change, but should work

### CODE REVIEW

**Comment by jsardev** [comment]
@signed-log Thanks for the PR! I wonder - why not use one of the [official .NET docker images](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/official-net-docker-images)? Bitnami is a 3rd party AFAIK (and not sure if the image is any lightweight 🤔 ). Will try to test it out in the following week.

**Comment by signed-log** [comment]
I didn't know they actually existed

Bitnami is a VMWare program that produces many software images and has been really reliable for me

**Comment by jsardev** [comment]
The [smallest official image](https://mcr.microsoft.com/en-us/product/dotnet/sdk/tags) (7.0-alpine-amd64) is 240 MB, and the [bitnami/dotnet-sdk](https://hub.docker.com/r/bitnami/dotnet-sdk/tags) is 374.44 MB. Not a huge improvement, but I think worth trying.

I often worry about the weight as container registries are not free and you need to host it somewhere 😅 

Anyways, I'll try to test it out in the next few days 😃

**Comment by ilkerogutcu** [comment]
I tried to run the project with my dockerfile, but I'm getting an error when trying to retrieve the vioshield value. I think the reason for the error is related to the chrome driver because I'm using Selenium in the project. Do you know anything about this?

**Comment by signed-log** [comment]
Oh, it uses chromedriver? I will not work in this state at all, will fix as soon as possible

**Comment by ilkerogutcu** [comment]
Yes, I had to use Selenium to bypass Cloudflare.

**Comment by jsardev** [comment]
I had some time to work on this and created a separate [PR](https://github.com/ilkerogutcu/keydrop-giveaway-bot/pull/9). It works, so I guess we can close this one 😄

**Pull request closed without merging**
